package com.sample

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

import org.kie.api.runtime.KieRuntime;
import com.sample.BottleOfWineApp.Prompt;
import com.sample.Question;

rule "Ask who drinks"
    when
        not Info(getQuestion() == "whoDrinks")
        $question : Question(keyword == "whoDrinks")
    then
        insert($question.ask());
end

rule "Ask social gathering"
    when
    	not Info(getQuestion() == "socialGathering")
        Info(getQuestion() == "whoDrinks", toString() == "someoneElse")
        $question : Question(keyword == "socialGathering")
    then
        insert($question.ask());
end

rule "Ask which social gathering"
    when
    	not Info(getQuestion() == "whichSocialGathering")
        Info(getQuestion() == "socialGathering", toString() == "yes")
        $question : Question(keyword == "whichSocialGathering")
    then
        insert($question.ask());
end

rule "Ask know people"
    when
    	not Info(getQuestion() == "knowPeople")
    	Info((getQuestion() == "whichSocialGathering" && toString() == "getTogether") ||
    		 (getQuestion() == "socialGathering" && toString() == "no"))
        $question : Question(keyword == "knowPeople")
    then
        insert($question.ask());
end

rule "Ask do people love wine"
    when
    	not Info(getQuestion() == "doPeopleLoveWine")
    	Info(getQuestion() == "knowPeople" && toString() == "yes")
        $question : Question(keyword == "doPeopleLoveWine")
    then
        insert($question.ask());
end

rule "Ask people favorite"
    when
    	not Info(getQuestion() == "peopleFavorite")
    	Info((getQuestion() == "whichSocialGathering" && toString() == "getTogether") ||
    		 (getQuestion() == "socialGathering" && toString() == "no"))
        $question : Question(keyword == "peopleFavorite")
    then
        insert($question.ask());
end

rule "Ask who is cooking"
    when
    	not Info(getQuestion() == "whoIsCooking")
    	Info(getQuestion() == "whichSocialGathering" && toString() == "dinnerParty")
        $question : Question(keyword == "whoIsCooking")
    then
        insert($question.ask());
end

rule "Ask at home"
    when
    	not Info(getQuestion() == "atHome")
    	Info(getQuestion() == "whoDrinks" && toString() == "personalUse")
        $question : Question(keyword == "atHome")
    then
        insert($question.ask());
end

rule "Ask alone"
    when
    	not Info(getQuestion() == "alone")
    	Info((getQuestion() == "atHome" && toString() == "yes") ||
    		 (getQuestion() == "special" && toString() == "newYear"))
        $question : Question(keyword == "alone")
    then
        insert($question.ask());
end

rule "Ask recovering from work"
    when
    	not Info(getQuestion() == "recoveringFromWork")
    	Info(getQuestion() == "alone" && toString() == "yes")
    	not Info(getQuestion() == "dailyDrinking" && toString() == "no")
        $question : Question(keyword == "recoveringFromWork")
    then
        insert($question.ask());
end

rule "Ask getting drunk"
    when
    	not Info(getQuestion() == "gettingDrunk")
    	Info(getQuestion() == "alone" && toString() == "yes")
    	Info(getQuestion() == "atHome" && toString() == "yes")
    	not Info(getQuestion() == "dailyDrinking" && toString() == "no")
        $question : Question(keyword == "gettingDrunk")
    then
        insert($question.ask());
end

rule "Ask feeling fancy 1"
    when
    	not Info(getQuestion() == "feelingFancy")
    	Info(getQuestion() == "where" && toString() == "restaurant")
        $question : Question(keyword == "feelingFancy")
    then
        insert($question.ask());
end

rule "Ask feeling fancy 2"
    when
    	not Info(getQuestion() == "feelingFancy")
    	Info(getQuestion() == "alone" && toString() == "yes")
    	not Info(getQuestion() == "dailyDrinking" && toString() == "no")
    	Info(getQuestion() == "atHome" && toString() == "yes")
        $question : Question(keyword == "feelingFancy")
    then
        insert($question.ask());
end

rule "Ask daily drinking"
    when
        $prompt : Prompt(hasInfo("alone", "yes") == true,
       					 hasInfo("atHome", "yes") == true,
        				 hasInfo("dailyDrinking") == false)
        $question : Question(keyword == "dailyDrinking")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask kool aid man"
    when
        $prompt : Prompt(hasInfo("dailyDrinking", "yes") == true,
        				 hasInfo("koolAidMan") == false)
        $question : Question(keyword == "koolAidMan")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask eat dirt as a child"
    when
        $prompt : Prompt(hasInfo("dailyDrinking", "yes") == true,
        				 hasInfo("eatDirtAsAChild") == false)
        $question : Question(keyword == "eatDirtAsAChild")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask spray butter"
    when
        $prompt : Prompt(hasInfo("dailyDrinking", "yes") == true,
        				 hasInfo("sprayButter") == false)
        $question : Question(keyword == "sprayButter")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask new or old"
    when
        $prompt : Prompt((hasInfo("dailyDrinking", "no") == true ||
        				  hasInfo("pronounce", "yes")),
        				 hasInfo("newOrOld") == false)
        $question : Question(keyword == "newOrOld")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask cults"
    when
        $prompt : Prompt(hasInfo("newOrOld", "new") == true,
        				 hasInfo("cults") == false)
        $question : Question(keyword == "cults")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask where"
    when
        $prompt : Prompt(hasInfo("atHome", "no") == true,
        				 hasInfo("where") == false)
        $question : Question(keyword == "where")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask wine is main course"
    when
        $prompt : Prompt(hasInfo("where", "dinner") == true,
        				 hasInfo("wineIsainCourse") == false)
        $question : Question(keyword == "wineIsainCourse")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask from microwave"
    when
        $prompt : Prompt(hasInfo("wineIsMainCourse", "no") == true,
        				 hasInfo("fromMicrowave") == false)
        $question : Question(keyword == "fromMicrowave")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask cook with wine"
    when
        $prompt : Prompt(hasInfo("fromMicrowave", "no") == true,
        				 hasInfo("cookWithWine") == false)
        $question : Question(keyword == "cookWithWine")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask pronounce"
    when
        $prompt : Prompt(hasInfo("feelingFancy", "yes") == true,
        				 hasInfo("pronounce") == false)
        $question : Question(keyword == "pronounce")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask special"
    when
        $prompt : Prompt(hasInfo("where", "special") == true,
        				 hasInfo("special") == false)
        $question : Question(keyword == "special")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask old"
    when
        $prompt : Prompt(hasInfo("special", "birthday") == true,
        				 hasInfo("old") == false)
        $question : Question(keyword == "old")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask first anniversary"
    when
        $prompt : Prompt(hasInfo("special", "anniversary") == true,
        				 hasInfo("firstAnniversary") == false)
        $question : Question(keyword == "firstAnniversary")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end


//////////////replys

rule "reply Get out 2 "
    when
        $prompt : Prompt((hasInfo("peopleFavorite", "no")&&hasInfo("socialGathering","no") == true)||
        (hasInfo("knowPeople", "no")&&hasInfo("socialGathering","no") == true)||
        (hasInfo("doPeopleLoveWine", "no")&&hasInfo("socialGathering","no")==true)       				
        				 )
        $response : Response(keyword == "GetOut2")
    then
    	$response.reply();
end



rule " reply 2 buck"
    when
        $prompt : Prompt(hasInfo("artOpening") == true )
        $response : Response(keyword == "NoTasteArt")
    then
        $response.reply();
end

rule " reply no glass"
    when
        $prompt : Prompt(hasInfo("beachBbq") == true )
        $response : Response(keyword == "NoGlass")
    then
        $response.reply();
end

rule " reply red blend "
    when
        $prompt : Prompt(hasInfo("whoIsCooking", "them") == true )
        $response : Response(keyword == "BiggestRed")
    then
        $response.reply();
end



rule " reply vodka"
    when
        $prompt : Prompt(hasInfo("bachelorParty") == true )
        $response : Response(keyword == "WhiskyVodka")
    then
        $response.reply();
end

rule " get out 2  "
    when
        $prompt : Prompt( 
        				 (hasInfo("doPeopleLoveWine","no")==true && hasInfo("knowPeople","yes")==true && hasInfo("socialGathering","yes")==true   )
        				|| (hasInfo("whoIsCooking","me") == true) 
        				 )
        $response : Response(keyword == "GetOut2")
    then
        $response.reply();
end

rule " boring  "
    when
        $prompt : Prompt(hasInfo("getTogether"), hasInfo("knowPeople","no")==true) 
        					
        $response : Response(keyword == "NoOpen")
    then
        $response.reply();
end

rule " pinot noir  "
    when
        $prompt : Prompt(hasInfo("recoveringFromWork","yes")==true)
        $response : Response(keyword == "PinotNoir")
    then
        $response.reply();
end

rule " cali pinot noir  "
    when
        $prompt : Prompt(
        (hasInfo("peopleFavorite","yes")==true) ||
        (hasInfo("firstAnniversary","yes")==true) ||
        (hasInfo("birthday")&&hasInfo("old","yes")==true)
        )
        				 
        $response : Response(keyword == "CaliPinotNoir")
    then
        $response.reply();
end

rule " merlot  "
    when
        $prompt : Prompt( hasInfo("firstAnniversary","no")==true)
        
        $response : Response(keyword == "Merlot")
    then
        $response.reply();
end

rule " zinfandel  or shiraz"
    when
        $prompt : Prompt( hasInfo("gettingDrunk","yes")==true)
        
        $response : Response(keyword == "HighOctane")
    then
        $response.reply();
end

rule " sangiovese grenache "
    when
        $prompt : Prompt( hasInfo("feelingFancy","yes")==true || 
        ( hasInfo("wineIsMainCourse","yes"))==true ||
        ( hasInfo("alone","yes")&& hasInfo("newYear","yes"))==true )
        
        $response : Response(keyword == "Exotic")
    then
        $response.reply();
end

rule " argentinian malblec  "
    when
        $prompt : Prompt( hasInfo("koolAidMan","yes")==true)
        
   		$response : Response(keyword == "ArgMalblec")
    then
        $response.reply();
end

rule " chinono burgueil   "
    when
        $prompt : Prompt( hasInfo("eatDirtAsAChild","yes")==true)
        
        $response : Response(keyword == "Chinon_Bourgeil")
    then
        $response.reply();
end

rule " buttery chardonay  "
    when
        $prompt : Prompt( hasInfo("sprayButter","yes")==true)
        
        $response : Response(keyword == "ButteryChardonay")
    then
        $response.reply();
end

rule " big box wine  "
    when
        $prompt : Prompt( (hasInfo("fromMicrowave","yes")==true) ||(hasInfo("orderFromWindow","yes")==true))
        
        $response : Response(keyword == "BigBoxWine")
    then
        $response.reply();
end

rule " get out 1   "
    when
        $prompt : Prompt( (hasInfo("sprayButter","no")==true)||
        (hasInfo("newOrOld","dunno")==true))
        
        $response : Response(keyword == "GetOut1")
    then
        $response.reply();
end

rule " bordox or burgundy  "
    when
        $prompt : Prompt(hasInfo("newOrOld","old")==true)
        
        $response : Response(keyword == "Bordoux_Burgundy")
    then
        $response.reply();
end

rule " cali cabernet  "
    when
        $prompt : Prompt((hasInfo("orderFromWindow","no")==true) || (hasInfo("cults","no")==true))
        
        $response : Response(keyword == "CaliCabernet")
    then
        $response.reply();
end

rule " sauvignion blanc  "
    when
        $prompt : Prompt(hasInfo("cookWithWine","yes")==true)
        
        $response : Response(keyword == "SauvignioneBlanc")
    then
        $response.reply();
end

rule " sine qua non , cayuse  "
    when
        $prompt : Prompt(hasInfo("cults","yes")==true)
        
        $response : Response(keyword == "SQN_Cayuse")
    then
        $response.reply();
end

rule " cotes du rhone  "
    when
        $prompt : Prompt(hasInfo("pronounce","no")==true)
        
        $response : Response(keyword == "CotesRhone")
    then
        $response.reply();
end

rule " small box wine "
    when
        $prompt : Prompt( (hasInfo("camping")==true) || (hasInfo("drinkingInPublic")==true))
        
        $response : Response(keyword == "SmallBoxWine")
    then
        $response.reply();
end

rule " spanish cava  "
    when
        $prompt : Prompt( (hasInfo("newYear")==true) || (hasInfo("alone")==true))
        
        $response : Response(keyword == "SpanishCava")
    then
        $response.reply();
end

rule " riesling or chenin  "
    when
        $prompt : Prompt( (hasInfo("birthday")==true&&hasInfo("old","no")==true) || (hasInfo("blindDate")==true)||
        (hasInfo("eloping")==true))
        
        $response : Response(keyword == "RiesChenin")
    then
        $response.reply();
end










