package com.sample

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

import org.kie.api.runtime.KieRuntime;
import com.sample.BottleOfWineApp.Prompt;
import com.sample.Question;

rule "Ask who drinks"
    when
        $prompt : Prompt(hasInfo("whoDrinks") == false)
        $question : Question(keyword == "whoDrinks")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask social gathering"
    when
        $prompt : Prompt(hasInfo("whoDrinks", "someoneElse") == true &&
        				 hasInfo("socialGathering") == false)
        $question : Question(keyword == "socialGathering")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask which social gathering"
    when
        $prompt : Prompt(hasInfo("socialGathering", "yes") == true,
        				 hasInfo("whichSocialGathering") == false)
        $question : Question(keyword == "whichSocialGathering")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask know people"
    when
        $prompt : Prompt((hasInfo("whichSocialGathering", "getTogether") == true ||
        				 hasInfo("socialGathering", "no") == true),
        				 hasInfo("knowPeople") == false)
        $question : Question(keyword == "knowPeople")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask do people love wine"
    when
        $prompt : Prompt(hasInfo("knowPeople", "yes") == true &&
        				 hasInfo("doPeopleLoveWine") == false)
        $question : Question(keyword == "doPeopleLoveWine")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask people favorite"
    when
        $prompt : Prompt((hasInfo("whichSocialGathering", "getTogether") == true ||
        				 hasInfo("socialGathering", "no") == true),
        				 hasInfo("peopleFavorite") == false)
        $question : Question(keyword == "peopleFavorite")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask who is cooking"
    when
        $prompt : Prompt(hasInfo("whichSocialGathering", "dinnerParty") == true,
        				 hasInfo("whoIsCooking") == false)
        $question : Question(keyword == "whoIsCooking")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask at home"
    when
        $prompt : Prompt(hasInfo("whoDrinks", "personalUse") == true,
        				 hasInfo("atHome") == false)
        $question : Question(keyword == "atHome")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask alone"
    when
        $prompt : Prompt((hasInfo("atHome", "yes") == true ||
        				  hasInfo("special", "newYear") == true),
        				 hasInfo("alone") == false)
        $question : Question(keyword == "alone")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask recovering from work"
    when
        $prompt : Prompt(hasInfo("alone", "yes") == true,
        				 hasInfo("recoveringFromWork") == false,
        				 hasInfo("dailyDrinking", "no") == false)
        $question : Question(keyword == "recoveringFromWork")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask getting drunk"
    when
        $prompt : Prompt(hasInfo("alone", "yes") == true,
       					 hasInfo("atHome", "yes") == true,
       					 hasInfo("dailyDrinking", "no") == false,
        				 hasInfo("gettingDrunk") == false)
        $question : Question(keyword == "gettingDrunk")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask feeling fancy"
    when
        $prompt : Prompt((hasInfo("alone", "yes") == true && // FIXME: missmatched input ","
       					  hasInfo("atHome", "yes") == true &&
       					  hasInfo("dailyDrinking", "no") == false &&
        				  hasInfo("feelingFancy") == false) ||
        				 hasInfo("where", "restaurant") == true)
        $question : Question(keyword == "feelingFancy")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask daily drinking"
    when
        $prompt : Prompt(hasInfo("alone", "yes") == true,
       					 hasInfo("atHome", "yes") == true,
        				 hasInfo("dailyDrinking") == false)
        $question : Question(keyword == "dailyDrinking")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask kool aid man"
    when
        $prompt : Prompt(hasInfo("dailyDrinking", "yes") == true,
        				 hasInfo("koolAidMan") == false)
        $question : Question(keyword == "koolAidMan")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask eat dirt as a child"
    when
        $prompt : Prompt(hasInfo("dailyDrinking", "yes") == true,
        				 hasInfo("eatDirtAsAChild") == false)
        $question : Question(keyword == "eatDirtAsAChild")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask spray butter"
    when
        $prompt : Prompt(hasInfo("dailyDrinking", "yes") == true,
        				 hasInfo("sprayButter") == false)
        $question : Question(keyword == "sprayButter")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask new or old"
    when
        $prompt : Prompt((hasInfo("dailyDrinking", "no") == true ||
        				  hasInfo("pronounce", "yes")),
        				 hasInfo("newOrOld") == false)
        $question : Question(keyword == "newOrOld")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask cults"
    when
        $prompt : Prompt(hasInfo("newOrOld", "new") == true,
        				 hasInfo("cults") == false)
        $question : Question(keyword == "cults")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask where"
    when
        $prompt : Prompt(hasInfo("atHome", "no") == true,
        				 hasInfo("where") == false)
        $question : Question(keyword == "where")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask wine is main course"
    when
        $prompt : Prompt(hasInfo("where", "dinner") == true,
        				 hasInfo("wineIsainCourse") == false)
        $question : Question(keyword == "wineIsainCourse")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask from microwave"
    when
        $prompt : Prompt(hasInfo("wineIsMainCourse", "no") == true,
        				 hasInfo("fromMicrowave") == false)
        $question : Question(keyword == "fromMicrowave")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask cook with wine"
    when
        $prompt : Prompt(hasInfo("fromMicrowave", "no") == true,
        				 hasInfo("cookWithWine") == false)
        $question : Question(keyword == "cookWithWine")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask pronounce"
    when
        $prompt : Prompt(hasInfo("feelingFancy", "yes") == true,
        				 hasInfo("pronounce") == false)
        $question : Question(keyword == "pronounce")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask special"
    when
        $prompt : Prompt(hasInfo("where", "special") == true,
        				 hasInfo("special") == false)
        $question : Question(keyword == "special")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask old"
    when
        $prompt : Prompt(hasInfo("special", "birthday") == true,
        				 hasInfo("old") == false)
        $question : Question(keyword == "old")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end

rule "Ask first anniversary"
    when
        $prompt : Prompt(hasInfo("special", "anniversary") == true,
        				 hasInfo("firstAnniversary") == false)
        $question : Question(keyword == "firstAnniversary")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end


//////////////replys

rule "reply Get out 2 "
    when
        $prompt : Prompt((hasInfo("peopleFavorite", "no")&&hasInfo("socialGathering","no") == true)||
        (hasInfo("knowPeople", "no")&&hasInfo("socialGathering","no") == true)||
        (hasInfo("doPeopleLoveWine", "no")&&hasInfo("socialGathering","no")==true)       				
        				 )
       
    then
        $ui.reply_final("GetOut2");
        update($prompt);
end



rule " reply 2 buck"
    when
        $prompt : Prompt(hasInfo("artOpening") == true )
        //$question : Question(keyword == "knowPeople")   //to 2 buckshot
    then
        $ui.reply_final("NoTasteArt");
        update($prompt);
end

rule " reply no glass"
    when
        $prompt : Prompt(hasInfo("beachBbq") == true )
        //$question : Question(keyword == "knowPeople")   //to  noglass
    then
        $ui.reply_final("NoGlass");
        update($prompt);
end

rule " reply red blend "
    when
        $prompt : Prompt(hasInfo("whoIsCooking", "them") == true )
        //$question : Question(keyword == "knowPeople")   //to  red blend
    then
        $ui.reply_final("BiggestRed");
        update($prompt);
end



rule " reply vodka"
    when
        $prompt : Prompt(hasInfo("bachelorParty") == true )
        //$question : Question(keyword == "knowPeople")   //to  vodka
    then
        $ui.reply_final("WhiskyVodka");
        update($prompt);
end

rule " get out 2  "
    when
        $prompt : Prompt( 
        				 (hasInfo("doPeopleLoveWine","no")==true && hasInfo("knowPeople","yes")==true && hasInfo("socialGathering","yes")==true   )
        				|| (hasInfo("whoIsCooking","me") == true) 
        				 )
        //$question : Question(keyword == "knowPeople")   //to  vwypad
    then
        $ui.reply_final("GetOut2");
        update($prompt);
end

rule " boring  "
    when
        $prompt : Prompt(hasInfo("getTogether"), hasInfo("knowPeople","no")==true) 
        					
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("NoOpen");
        update($prompt);
end

rule " pinot noir  "
    when
        $prompt : Prompt(hasInfo("recoveringFromWork","yes")==true)
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("PinotNoir");
        update($prompt);
end

rule " cali pinot noir  "
    when
        $prompt : Prompt(
        (hasInfo("peopleFavorite","yes")==true) ||
        (hasInfo("firstAnniversary","yes")==true) ||
        (hasInfo("birthday")&&hasInfo("old","yes")==true)
        )
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("CaliPinotNoir");
        update($prompt);
end

rule " merlot  "
    when
        $prompt : Prompt( hasInfo("firstAnniversary","no")==true)
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("Merlot");
        update($prompt);
end

rule " zinfandel  or shiraz"
    when
        $prompt : Prompt( hasInfo("gettingDrunk","yes")==true)
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("HighOctane");
        update($prompt);
end

rule " sangiovese grenache "
    when
        $prompt : Prompt( hasInfo("feelingFancy","yes")==true || 
        ( hasInfo("wineIsMainCourse","yes"))==true ||
        ( hasInfo("alone","yes")&& hasInfo("newYear","yes"))==true )
        
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("Exotic");
        update($prompt);
end

rule " argentinian malblec  "
    when
        $prompt : Prompt( hasInfo("koolAidMan","yes")==true)
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("ArgMalblec");
        update($prompt);
end

rule " chinono burgueil   "
    when
        $prompt : Prompt( hasInfo("eatDirtAsAChild","yes")==true)
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("Chinon_Bourgeil");
        update($prompt);
end

rule " buttery chardonay  "
    when
        $prompt : Prompt( hasInfo("sprayButter","yes")==true)
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("ButteryChardonay");
        update($prompt);
end

rule " big box wine  "
    when
        $prompt : Prompt( (hasInfo("fromMicrowave","yes")==true) ||(hasInfo("orderFromWindow","yes")==true)
        
        				 )
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("BigBoxWine");
        update($prompt);
end

rule " get out 1   "
    when
        $prompt : Prompt( (hasInfo("sprayButter","no")==true)||
        (hasInfo("newOrOld","dunno")==true))
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("GetOut1");
        update($prompt);
end

rule " bordox or burgundy  "
    when
        $prompt : Prompt(hasInfo("newOrOld","old")==true)
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("Bordoux_Burgundy");
        update($prompt);
end

rule " cali cabernet  "
    when
        $prompt : Prompt((hasInfo("orderFromWindow","no")==true) || (hasInfo("cults","no")==true))
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("CaliCabernet");
        update($prompt);
end

rule " sauvignion blanc  "
    when
        $prompt : Prompt(hasInfo("cookWithWine","yes")==true)
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("SauvignioneBlanc");
        update($prompt);
end

rule " sine qua non , cayuse  "
    when
        $prompt : Prompt(hasInfo("cults","yes")==true)
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("SQN_Cayuse");
        update($prompt);
end

rule " cotes du rhone  "
    when
        $prompt : Prompt(hasInfo("pronounce","no")==true)
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("CotesRhone");
        update($prompt);
end

rule " small box wine "
    when
        $prompt : Prompt( (hasInfo("camping")==true) || (hasInfo("drinkingInPublic")==true))
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("SmallBoxWine");
        update($prompt);
end

rule " spanish cava  "
    when
        $prompt : Prompt( (hasInfo("newYear")==true) || (hasInfo("alone")==true))
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("SpanishCava");
        update($prompt);
end

rule " riesling or chenin  "
    when
        $prompt : Prompt( (hasInfo("birthday")&&hasInfo("old","no")==true) || (hasInfo("blindDate")==true)||
        (hasInfo("eloping")==true))
        
        				 
        //$question : Question(keyword == "knowPeople")   //modyfikuj
    then
        $ui.reply_final("RiesChenin");
        update($prompt);
end










