package com.sample

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

import org.kie.api.runtime.KieRuntime;
import com.sample.BottleOfWineApp.Prompt;
import com.sample.Question;

rule "Is working"
	when
	then
		System.out.println("Is working");
end

rule "Ask who drinks"
    when
        $prompt : Prompt(hasInfo("whoDrinks") == false)
        $question : Question(keyword == "whoDrinks")
    then
        $prompt.addInfo($question.ask());
        update($prompt);
end
